# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'findWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 241)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.find_text = QtWidgets.QLineEdit(Form)
        self.find_text.setObjectName("find_text")
        self.horizontalLayout.addWidget(self.find_text)
        self.btn_find = QtWidgets.QPushButton(Form)
        self.btn_find.setObjectName("btn_find")
        self.horizontalLayout.addWidget(self.btn_find)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ai_checkBox = QtWidgets.QCheckBox(Form)
        self.ai_checkBox.setObjectName("ai_checkBox")
        self.horizontalLayout_2.addWidget(self.ai_checkBox)
        self.regex_checkBox = QtWidgets.QCheckBox(Form)
        self.regex_checkBox.setObjectName("regex_checkBox")
        self.horizontalLayout_2.addWidget(self.regex_checkBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.combo_searchfor = QtWidgets.QComboBox(Form)
        self.combo_searchfor.setObjectName("combo_searchfor")
        self.horizontalLayout_3.addWidget(self.combo_searchfor)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.preview_text = QtWidgets.QPlainTextEdit(Form)
        self.preview_text.setObjectName("preview_text")
        self.verticalLayout.addWidget(self.preview_text)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.strings_length = QtWidgets.QLineEdit(Form)
        self.strings_length.setObjectName("strings_length")
        self.horizontalLayout_4.addWidget(self.strings_length)
        self.btn_add_strings = QtWidgets.QPushButton(Form)
        self.btn_add_strings.setObjectName("btn_add_strings")
        self.horizontalLayout_4.addWidget(self.btn_add_strings)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Find"))
        self.label.setText(_translate("Form", "Find what:"))
        self.btn_find.setText(_translate("Form", "Find"))
        self.ai_checkBox.setText(_translate("Form", "AI"))
        self.regex_checkBox.setText(_translate("Form", "Regex"))
        self.label_2.setText(_translate("Form", "Search in:"))
        self.label_3.setText(_translate("Form", "Preview:"))
        self.label_4.setText(_translate("Form", "Min Length:"))
        self.strings_length.setText(_translate("Form", "4"))
        self.btn_add_strings.setText(_translate("Form", "Add Column with Strings"))
